#TraP Score, Added by Phil Richmond
[[annotation]]
file="/mnt/causes-data01/data/Databases/GEMINI/TrAP/FullTraPv2.txt.gz"
names=["TraP_gene","TraP_score"]
columns=[3,4]
ops=["self","self"]

#gnomAD Allele Frequency (all) and Homozygous Count (all), added by Phil Richmond
[[annotation]]
file="/mnt/causes-data01/data/Databases/GNOMAD/gnomad.genomes.r2.0.1.sites.wholeGenome.norm.vcf.gz"
fields = ["AF","Hom"]
names = ["aaf_gnomAD_genome_all","gnomAD_genome_num_hom_alt"]
ops = ["self","self"]

#Count from in-house database, added by Phil Richmond
[[annotation]]
file="/mnt/causes-data01/data/Databases/InHouseDatabase/MergedVCF.20170911.norm.vcf.gz"
fields = ["AC"]
names = ["InHouseDB_AC"]
ops = ["self"]



# ExAC 
[[annotation]]
file="/opt/tools/gemini-0.19.1/thirdparty/gemini_data/ExAC.r0.3.sites.vep.tidy.vcf.gz"
fields = ["AC_Adj", "AN_Adj", "AC_AFR", "AN_AFR", "AC_AMR", "AN_AMR", "AC_EAS", "AN_EAS", "AC_FIN", "AN_FIN", "AC_NFE", "AN_NFE", "AC_OTH", "AN_OTH", "AC_SAS", "AN_SAS", 
          "AC_Het", "AC_Hom"]
names = ["ac_exac_all", "an_exac_all", "ac_adj_exac_afr", "an_adj_exac_afr", "ac_adj_exac_amr", "an_adj_exac_amr", "ac_adj_exac_eas", "an_adj_exac_eas", "ac_adj_exac_fin", "an_adj_exac_fin", "ac_adj_exac_nfe", "an_adj_exac_nfe", "ac_adj_exac_oth", "an_adj_exac_oth", "ac_adj_exac_sas", "an_adj_exac_sas",
          "num_exac_Het", "num_exac_Hom"]
ops=["max", "self", "max", "self", "max", "self", "max", "self", "max", "self", "max", "self", "max", "self", "max", "self", "self", "self"] 


# Exome Sequencing Project
[[annotation]]
file="/opt/tools/gemini-0.19.1/thirdparty/gemini_data/ESP6500SI.all.snps_indels.tidy.v2.vcf.gz"
fields=["EA_AC", "AA_AC", "TAC"]
names=["af_esp_ea_float", "af_esp_aa_float", "af_esp_all_float"]
ops=["lua:ratio(vals)", "lua:ratio(vals)", "lua:ratio(vals)"]

# dbSNP rsIds
[[annotation]]
file="/opt/tools/gemini-0.19.1/thirdparty/gemini_data/dbsnp.b147.20160601.tidy.vcf.gz"
fields=["ID"]
names=["rs_ids"]
ops=["concat"]

# 1k Genomes
[[annotation]]
file="/opt/tools/gemini-0.19.1/thirdparty/gemini_data/ALL.wgs.phase3_shapeit2_mvncall_integrated_v5a.20130502.sites.tidy.vcf.gz"
fields=["AMR_AF", "EAS_AF", "SAS_AF", "AFR_AF", "EUR_AF", "AF"]
names=["af_1kg_amr", "af_1kg_eas", "af_1kg_sas", "af_1kg_afr", "af_1kg_eur", "af_1kg_all"]
ops=["max", "max", "max", "max", "max", "max"]

# ClinVar (
[[annotation]]
file="/mnt/causes-data01/data/Databases/GEMINI/clinvar_20171231.vcf.gz"
fields=["CLNSIG", "CLNDN","CLNDISDB"]
names=["clinvar_pathogenic", "clinvar_disease_name","clinvar_dbInfo"]
ops=["self", "self", "self"]

# convert 5 to 'pathogenic', 255 to 'unknown', etc.
[[postannotation]]
fields=["clinvar_pathogenic"]
op="lua:clinvar_sig(clinvar_pathogenic)"
name="clinvar_sig"
type="String"

# calculate allele frequencies for all populations.
[[postannotation]]
fields=["ac_exac_all", "an_exac_all"]
name="af_exac_all"
op="div2"
type="Float"

[[postannotation]]
fields=["ac_adj_exac_afr", "an_adj_exac_afr"]
name="af_adj_exac_afr"
op="div2"
type="Float"

[[postannotation]]
fields=["ac_adj_exac_amr", "an_adj_exac_amr"]
name="af_adj_exac_amr"
op="div2"
type="Float"

[[postannotation]]
fields=["ac_adj_exac_eas", "an_adj_exac_eas"]
name="af_adj_exac_eas"
op="div2"
type="Float"

[[postannotation]]
fields=["ac_adj_exac_fin", "an_adj_exac_fin"]
name="af_adj_exac_fin"
op="div2"
type="Float"

[[postannotation]]
fields=["ac_adj_exac_nfe", "an_adj_exac_nfe"]
name="af_adj_exac_nfe"
op="div2"
type="Float"

[[postannotation]]
fields=["ac_adj_exac_oth", "an_adj_exac_oth"]
name="af_adj_exac_oth"
op="div2"
type="Float"

[[postannotation]]
fields=["ac_adj_exac_sas", "an_adj_exac_sas"]
name="af_adj_exac_sas"
op="div2"
type="Float"


[[postannotation]]
fields=['af_adj_exac_afr', 'af_adj_exac_amr', 'af_adj_exac_eas', 'af_adj_exac_fin', 'af_adj_exac_nfe', 'af_adj_exac_oth', 'af_adj_exac_sas', "af_esp_ea", "af_esp_aa", "af_esp_all", "af_1kg_amr", "af_1kg_eas", "af_1kg_sas", "af_1kg_afr", "af_1kg_eur", "af_1kg_all"]
op="max"
name="max_aaf_all"
type="Float"

[[postannotation]]
fields=["clinvar_sig", "max_aaf_all"]
op="lua:check_clinvar_aaf(clinvar_sig, max_aaf_all, 0.005)"
name="common_pathogenic"
type="Flag"

[[annotation]]
file="/opt/tools/gemini-0.19.1/thirdparty/gemini_data/cosmic-v68-GRCh37.tidy.vcf.gz"
fields=["ID"]
names=["cosmic_ids"]
ops=["uniq"]


[[annotation]]
file="/opt/tools/gemini-0.19.1/thirdparty/gemini_data/hg19_fitcons_fc-i6-0_V1-01.bed.gz"
columns=[4]
names=["fitcons_float"]
ops=["mean"]



#[[annotation]]
#file="/opt/tools/gemini-0.19.1/thirdparty/gemini_data/LCR-hs37d5.bed.gz"
#names=["LCR"]
#columns=[2]
#ops=["flag"]
#
#[[annotation]]
#http://humanparalogy.gs.washington.edu/build37/build37.htm
#  wget -O - http://humanparalogy.gs.washington.edu/build37/data/GRCh37GenomicSuperDup.tab \
#      | tail -n+2 \
#      | grep -Pv "_gl00|_random|chrUn" | sort -k1,1V -k2,2n | bgzip -c > GRCh37GenomicSuperDup.tab.gz
#file="GRCh37GenomicSuperDup.tab.gz"
#names=["superdup"]
#columns=[2]
#ops=["flag"]



[[annotation]]
file="/opt/tools/gemini-0.19.1/thirdparty/gemini_data/encode.6celltypes.consensus.bedg.gz"
#chrom   start   end     gm12878 h1hesc  helas3  hepg2   huvec   k562
columns=[4,5,6,7,8,9]
ops=["concat","concat", "concat", "concat", "concat", "concat"]
names=[ "encode_consensus_gm12878", "encode_consensus_h1hesc", "encode_consensus_helas3", "encode_consensus_hepg2", "encode_consensus_huvec", "encode_consensus_k562"]

[[annotation]]
file="/opt/tools/gemini-0.19.1/thirdparty/gemini_data/hg19.gwas.bed.gz"
columns=[4]
names=["gwas_pubmed_trait"]
ops=["uniq"]

[[annotation]]
file="/opt/tools/gemini-0.19.1/thirdparty/gemini_data/hg19.rmsk.bed.gz"
columns=[4]
names=["rmsk"]
ops=["uniq"]

[[annotation]]
file="/opt/tools/gemini-0.19.1/thirdparty/gemini_data/hg19.gerp.elements.bed.gz"
columns=[4]
names=["gerp_elements"]
ops=["mean"]

[[annotation]]
file="/opt/tools/gemini-0.19.1/thirdparty/gemini_data/hg19.CpG.bed.gz"
columns=[2]
names=["cpg_island"]
ops=["flag"]

[[annotation]]
file="/opt/tools/gemini-0.19.1/thirdparty/gemini_data/hg19.segdup.bed.gz"
columns=[2]
names=["in_segdup"]
ops=["flag"]

[[annotation]]
file="/opt/tools/gemini-0.19.1/thirdparty/gemini_data/hg19.dgv.bed.gz"
columns=[4]
names=["dgv"]
ops=["uniq"]

[[annotation]]
file="/opt/tools/gemini-0.19.1/thirdparty/gemini_data/wgEncodeRegTfbsClusteredV2.cell_count.20130213.bed.gz"
columns=[4]
names=["tfbs"]
ops=["uniq"]

[[annotation]]
file="/opt/tools/gemini-0.19.1/thirdparty/gemini_data/genetic_map_HapMapII_GRCh37.gz"
columns=[4, 5]
ops=["mean", "mean"]
names=["hapmap1", "hapmap2"]


[[annotation]]
file="/opt/tools/gemini-0.19.1/thirdparty/gemini_data/stam.125cells.dnaseI.hg19.bed.gz"
columns=[5, 6]
ops=["mean", "uniq"]
names=["stam_mean", "stam_names"]

[[annotation]]
file="/opt/tools/gemini-0.19.1/thirdparty/gemini_data/cse-hiseq-8_4-2013-02-20.bed.gz"
columns=[2]
ops=["flag"]
names=["cse-hiseq"]

[[annotation]]
file="/mnt/causes-data01/data/Databases/GEMINI/whole_genome_SNVs.tsv.gz"
names=["CADD"]
columns=[6]
ops=["self"]

[[annotation]]
file="/mnt/causes-data01/data/Databases/GEMINI/polyphen2/polyphen2.txt.gz"
names=["pp2hdiv", "pp2hvar"]
columns=[5, 6]
ops=["max", "max"]

