# This is the file read by VCFAnno that links to the database files for each annotation
# It is maintained by Phillip Richmond (phillip.a.richmond@gmail.com)
# If an annotation contains any post-annotations, then they will proceed the annotation call
# I have made new annotations here at the top of this file, while the ones that I took from Brent Pedersen are usually pointing to GEMINI databases
# Last edits: April 19 2018 (PAR)


# GeneHancer
[[annotation]]
file='/mnt/causes-data01/data/Databases/GEMINI/GeneHancer_hg19.sorted.bed.gz'
columns = [5]
names = ["GeneHancer"]
ops = ["self"]

# FATHMM-XF Noncoding
[[annotation]]
file = "/mnt/causes-data01/data/Databases/GEMINI/fathmm_xf_noncoding.vcf.gz"
columns = [5]
names = ["FATHMM-XF"]
ops = ["self"]

# ReMM
#[[annotation]]
#file = "/mnt/causes-data01/data/Databases/GEMINI/ReMM.v0.3.1.tsv.gz"
#columns = [3]
#names = ["ReMM"]
#ops = ["self"]

#gnomAD Allele Frequency (all) and Homozygous Count (all), added by Phil Richmond
[[annotation]]
file="/mnt/causes-data01/data/Databases/GNOMAD/gnomad.genomes.r2.0.1.sites.wholeGenome.norm.vcf.gz"
fields = ["AF","Hom","AF_AFR","Hom_AFR","AF_AMR","Hom_AMR","AF_ASJ","Hom_ASJ","AF_EAS","Hom_EAS","AF_FIN","Hom_FIN","AF_NFE","Hom_NFE","AF_OTH","Hom_OTH"]
names = ["aaf_gnomad_genome_all","gnomad_genome_num_hom_alt","gnomad_af_afr","gnomad_hom_afr","gnomad_af_amr","gnomad_hom_amr","gnomad_af_asj","gnomad_hom_asj","gnomad_af_eas","gnomad_hom_eas","gnomad_af_fin","gnomad_hom_fin","gnomad_af_nfe","gnomad_hom_nfe","gnomad_af_oth","gnomad_hom_oth"]
ops = ["self","self","self","self","self","self","self","self","self","self","self","self","self","self","self","self"]


#Count from in-house database, added by Phil Richmond
[[annotation]]
file="/mnt/causes-data01/data/Databases/InHouseDatabase/MergedVCF.20170911.norm.vcf.gz"
fields = ["AC"]
names = ["InHouseDB_AC"]
ops = ["self"]

# ExAC 
[[annotation]]
file="/opt/tools/gemini-0.19.1/thirdparty/gemini_data/ExAC.r0.3.sites.vep.tidy.vcf.gz"
fields = ["AC_Adj", "AN_Adj", "AC_AFR", "AN_AFR", "AC_AMR", "AN_AMR", "AC_EAS", "AN_EAS", "AC_FIN", "AN_FIN", "AC_NFE", "AN_NFE", "AC_OTH", "AN_OTH", "AC_SAS", "AN_SAS", 
          "AC_Het", "AC_Hom"]
names = ["ac_exac_all", "an_exac_all", "ac_adj_exac_afr", "an_adj_exac_afr", "ac_adj_exac_amr", "an_adj_exac_amr", "ac_adj_exac_eas", "an_adj_exac_eas", "ac_adj_exac_fin", "an_adj_exac_fin", "ac_adj_exac_nfe", "an_adj_exac_nfe", "ac_adj_exac_oth", "an_adj_exac_oth", "ac_adj_exac_sas", "an_adj_exac_sas",
          "num_exac_Het", "num_exac_Hom"]
ops=["max", "self", "max", "self", "max", "self", "max", "self", "max", "self", "max", "self", "max", "self", "max", "self", "self", "self"] 

# calculate allele frequencies for all populations.
[[postannotation]]
fields=["ac_exac_all", "an_exac_all"]
name="af_exac_all"
op="div2"
type="Float"

[[postannotation]]
fields=["ac_adj_exac_afr", "an_adj_exac_afr"]
name="af_adj_exac_afr"
op="div2"
type="Float"

[[postannotation]]
fields=["ac_adj_exac_amr", "an_adj_exac_amr"]
name="af_adj_exac_amr"
op="div2"
type="Float"

[[postannotation]]
fields=["ac_adj_exac_eas", "an_adj_exac_eas"]
name="af_adj_exac_eas"
op="div2"
type="Float"

[[postannotation]]
fields=["ac_adj_exac_fin", "an_adj_exac_fin"]
name="af_adj_exac_fin"
op="div2"
type="Float"

[[postannotation]]
fields=["ac_adj_exac_nfe", "an_adj_exac_nfe"]
name="af_adj_exac_nfe"
op="div2"
type="Float"

[[postannotation]]
fields=["ac_adj_exac_oth", "an_adj_exac_oth"]
name="af_adj_exac_oth"
op="div2"
type="Float"

[[postannotation]]
fields=["ac_adj_exac_sas", "an_adj_exac_sas"]
name="af_adj_exac_sas"
op="div2"
type="Float"

[[postannotation]]
fields=['af_adj_exac_afr', 'af_adj_exac_amr', 'af_adj_exac_eas', 'af_adj_exac_fin', 'af_adj_exac_nfe', 'af_adj_exac_oth', 'af_adj_exac_sas', "af_esp_ea", "af_esp_aa", "af_esp_all", "af_1kg_amr", "af_1kg_eas", "af_1kg_sas", "af_1kg_afr", "af_1kg_eur", "af_1kg_all"]
op="max"
name="max_aaf_all"
type="Float"

# Exome Sequencing Project
[[annotation]]
file="/opt/tools/gemini-0.19.1/thirdparty/gemini_data/ESP6500SI.all.snps_indels.tidy.v2.vcf.gz"
fields=["EA_AC", "AA_AC", "TAC"]
names=["af_esp_ea_float", "af_esp_aa_float", "af_esp_all_float"]
ops=["lua:ratio(vals)", "lua:ratio(vals)", "lua:ratio(vals)"]

# dbSNP rsIds
[[annotation]]
file="/opt/tools/gemini-0.19.1/thirdparty/gemini_data/dbsnp.b147.20160601.tidy.vcf.gz"
fields=["ID"]
names=["rs_ids"]
ops=["concat"]

# 1k Genomes
[[annotation]]
file="/opt/tools/gemini-0.19.1/thirdparty/gemini_data/ALL.wgs.phase3_shapeit2_mvncall_integrated_v5a.20130502.sites.tidy.vcf.gz"
fields=["AMR_AF", "EAS_AF", "SAS_AF", "AFR_AF", "EUR_AF", "AF"]
names=["af_1kg_amr", "af_1kg_eas", "af_1kg_sas", "af_1kg_afr", "af_1kg_eur", "af_1kg_all"]
ops=["max", "max", "max", "max", "max", "max"]

# ClinVar (Auto-updating)
[[annotation]]
file="/mnt/causes-data01/data/Databases/clinvar.vcf.gz"
fields=["CLNSIG", "CLNDN","CLNDISDB"]
names=["clinvar_pathogenic","clinvar_disease_name","clinvar_dbInfo"]

# ClinVar (Version from end of 2017)
#[[annotation]]
#file="/mnt/causes-data01/data/Databases/GEMINI/clinvar_20171231.vcf.gz"
#fields=["CLNSIG", "CLNDN","CLNDISDB"]
#names=["clinvar_pathogenic", "clinvar_disease_name","clinvar_dbInfo"]
#ops=["self", "self", "self"]

# convert 5 to 'pathogenic', 255 to 'unknown', etc.
#[[postannotation]]
#fields=["clinvar_pathogenic"]
#op="lua:clinvar_sig(clinvar_pathogenic)"
#name="clinvar_sig"
#type="String"

# Check for common, pathogenic variants
#[[postannotation]]
#fields=["clinvar_sig", "max_aaf_all"]
#op="lua:check_clinvar_aaf(clinvar_sig, max_aaf_all, 0.005)"
#name="common_pathogenic"
#type="Flag"

# Cosmic variants
[[annotation]]
file="/opt/tools/gemini-0.19.1/thirdparty/gemini_data/cosmic-v68-GRCh37.tidy.vcf.gz"
fields=["ID"]
names=["cosmic_ids"]
ops=["uniq"]

# Fitcons
[[annotation]]
file="/opt/tools/gemini-0.19.1/thirdparty/gemini_data/hg19_fitcons_fc-i6-0_V1-01.bed.gz"
columns=[4]
names=["fitcons_float"]
ops=["mean"]


# not sure what these are, encode I guess?
[[annotation]]
file="/opt/tools/gemini-0.19.1/thirdparty/gemini_data/encode.6celltypes.consensus.bedg.gz"
#chrom   start   end     gm12878 h1hesc  helas3  hepg2   huvec   k562
columns=[4,5,6,7,8,9]
ops=["concat","concat", "concat", "concat", "concat", "concat"]
names=[ "encode_consensus_gm12878", "encode_consensus_h1hesc", "encode_consensus_helas3", "encode_consensus_hepg2", "encode_consensus_huvec", "encode_consensus_k562"]

# Gwas hits
[[annotation]]
file="/opt/tools/gemini-0.19.1/thirdparty/gemini_data/hg19.gwas.bed.gz"
columns=[4]
names=["gwas_pubmed_trait"]
ops=["uniq"]

# Repeat masked regions
[[annotation]]
file="/opt/tools/gemini-0.19.1/thirdparty/gemini_data/hg19.rmsk.bed.gz"
columns=[4]
names=["rmsk"]
ops=["uniq"]

# GERP Elements
[[annotation]]
file="/opt/tools/gemini-0.19.1/thirdparty/gemini_data/hg19.gerp.elements.bed.gz"
columns=[4]
names=["gerp_elements"]
ops=["mean"]

#CpG Islands
[[annotation]]
file="/opt/tools/gemini-0.19.1/thirdparty/gemini_data/hg19.CpG.bed.gz"
columns=[2]
names=["cpg_island"]
ops=["flag"]

#Seg Dups
[[annotation]]
file="/opt/tools/gemini-0.19.1/thirdparty/gemini_data/hg19.segdup.bed.gz"
columns=[2]
names=["in_segdup"]
ops=["flag"]

# DGV hits
[[annotation]]
file="/opt/tools/gemini-0.19.1/thirdparty/gemini_data/hg19.dgv.bed.gz"
columns=[4]
names=["dgv"]
ops=["uniq"]

# TFBSs (NEED TO UPDATE THIS TO JASPAR)
[[annotation]]
file="/opt/tools/gemini-0.19.1/thirdparty/gemini_data/wgEncodeRegTfbsClusteredV2.cell_count.20130213.bed.gz"
columns=[4]
names=["tfbs"]
ops=["uniq"]

# HapMap II
[[annotation]]
file="/opt/tools/gemini-0.19.1/thirdparty/gemini_data/genetic_map_HapMapII_GRCh37.gz"
columns=[4, 5]
ops=["mean", "mean"]
names=["hapmap1", "hapmap2"]

# DNAse open regions
[[annotation]]
file="/opt/tools/gemini-0.19.1/thirdparty/gemini_data/stam.125cells.dnaseI.hg19.bed.gz"
columns=[5, 6]
ops=["mean", "uniq"]
names=["stam_mean", "stam_names"]

# Not sure what this is, CSE - HiSeq?
[[annotation]]
file="/opt/tools/gemini-0.19.1/thirdparty/gemini_data/cse-hiseq-8_4-2013-02-20.bed.gz"
columns=[2]
ops=["flag"]
names=["cse-hiseq"]

# CADD
[[annotation]]
file="/mnt/causes-data01/data/Databases/GEMINI/CADD_Try2/whole_genome_SNVs.tsv.gz"
names=["CADD"]
columns=[6]
ops=["self"]

# PolyPhen2
[[annotation]]
file="/mnt/causes-data01/data/Databases/GEMINI/polyphen2/polyphen2.txt.gz"
names=["pp2hdiv", "pp2hvar"]
columns=[5, 6]
ops=["max", "max"]

# High Confidence Regions
[[annotation]]
file="/mnt/causes-data01/data/Databases/ConfidentRegions/ConfidentRegions.bed.gz"
columns=[2]
names=["ConfidentRegion"]
ops=["flag"]



