# This is the file read by VCFAnno that links to the database files for each annotation
# It is maintained by Phillip Richmond (phillip.a.richmond@gmail.com)
# If an annotation contains any post-annotations, then they will proceed the annotation call
# I have made new annotations here at the top of this file, while the ones that I took from Brent Pedersen are usually pointing to GEMINI-2019 databases
# Last edits: April 19 2018 (PAR)
# Last edits: July 16 2018 (PAR) - added gnomad exome, dropped exac, 
# Last edits: August 20 2018 (PAR) - Moved away from /mnt/causes-data01/ to /mnt/causes-vnx1/
# Last edits: August 22nd 2018 (PAR) - Added eQTL
# Last edits: January 31st 2019 (PAR) - updated gnomAD, added CADD v1.4
# Last edits: February 28th, 2019 (PAR) - added CCR regions
# Last edits: March 21st, 2019 (PAR) It's my mothafuckin birthday!! But really, this was a huge update which was tested for functionality
	# new gnomad
	# spliceAI
	# FATHMM-XF-noncoding functional

# CCR - Conserved coding regions
[[annotation]]
file='CCR/ccrs.combined.v2.20180420.bed.gz'
columns = [4]
names = ['CCR']
ops = ['self']

# eQTL GTEX WholeBlood
[[annotation]]
file='eQTL/Whole_Blood_v7GTEXeQTL_sorted.vcf.gz'
fields = ["GENES"]
names = ["eQTL_GTEX_WholeBloodv7"]
ops = ["self"]

# GeneHancer
[[annotation]]
file='ENHANCERS/GeneHancer_hg19.sorted.bed.gz'
columns = [5]
names = ["GeneHancer"]
ops = ["self"]

# PrimateAI
[[annotation]]
file='PrimateAI_scores_v0.2_final.tsv.gz'
columns=[11]
names = ["PrimateAI"]
ops = ["self"]

# SpliceAI
[[annotation]]
file='SpliceAI/whole_genome_filtered_spliceai_scores.vcf.gz'
fields = ["DS_AG","DS_AL","DS_DG","DS_DL"]
names = ["SpliceAI_AcceptorGain","SpliceAI_AcceptorLoss","SpliceAI_DonorGain","SpliceAI_DonorLoss"]
ops = ["max","max","max","max"]

# FATHMM-XF Noncoding
[[annotation]]
file = "FATHMM/fathmm_xf_noncoding.tsv.gz"
columns = [5]
names = ["FATHMM_XF_NONCODING"]
ops = ["self"]

#gnomAD Genome Allele Frequency (all) and Homozygous Count (all), added by Phil Richmond
# Updated to v2.1
[[annotation]]
file="GNOMAD/v2.1/gnomad.genomes.r2.1.sites.vcf.gz"
fields = ["AF","nhomalt","AC","AN","popmax","AN_popmax","AC_popmax","AF_popmax","nhomalt_popmax","controls_AF","controls_nhomalt"]
names = ["gnomad_genome_af_global","gnomad_genome_hom_global","gnomad_genome_ac_global","gnomad_genome_an_global","gnomad_genome_popmax","gnomad_genome_an_popmax","gnomad_genome_ac_popmax","gnomad_genome_af_popmax","gnomad_genome_hom_popmax","gnomad_genome_af_controls","gnomad_genome_hom_controls"]
ops = ["self","self","self","self","self","self","self","self","self","self","self"]

#gnomAD Exome Allele Frequency
[[annotation]]
file="GNOMAD/v2.1/gnomad.exomes.r2.1.sites.vcf.gz"
fields = ["AF","nhomalt","AC","AN","popmax","AN_popmax","AC_popmax","AF_popmax","nhomalt_popmax","controls_AF","controls_nhomalt"]
names = ["gnomad_exome_af_global","gnomad_exome_hom_global","gnomad_exome_ac_global","gnomad_exome_an_global","gnomad_exome_popmax","gnomad_exome_an_popmax","gnomad_exome_ac_popmax","gnomad_exome_af_popmax","gnomad_exome_hom_popmax","gnomad_exome_af_controls","gnomad_exome_hom_controls"]
ops = ["self","self","self","self","self","self","self","self","self","self","self"]

#Count from in-house database, added by Phil Richmond
[[annotation]]
file="InHouseDatabase/MergedVCF.20170911.norm.vcf.gz"
fields = ["AC"]
names = ["InHouseDB_AC"]
ops = ["self"]

# Exome Sequencing Project
[[annotation]]
file="GEMINI-2019/gemini_data/ESP6500SI.all.snps_indels.tidy.v2.vcf.gz"
fields=["EA_AC", "AA_AC", "TAC"]
names=["af_esp_ea_float", "af_esp_aa_float", "af_esp_all_float"]
ops=["lua:ratio(vals)", "lua:ratio(vals)", "lua:ratio(vals)"]

# dbSNP rsIds
[[annotation]]
file="GEMINI-2019/gemini_data/dbsnp.151.20180423.tidy.vcf.gz"
fields=["ID"]
names=["rs_ids"]
ops=["concat"]

# 1k Genomes
[[annotation]]
file="GEMINI-2019/gemini_data/ALL.wgs.phase3_shapeit2_mvncall_integrated_v5a.20130502.sites.tidy.vcf.gz"
fields=["AMR_AF", "EAS_AF", "SAS_AF", "AFR_AF", "EUR_AF", "AF"]
names=["af_1kg_amr", "af_1kg_eas", "af_1kg_sas", "af_1kg_afr", "af_1kg_eur", "af_1kg_all"]
ops=["max", "max", "max", "max", "max", "max"]

# ClinVar (Auto-updating)
[[annotation]]
file="clinvar.vcf.gz"
fields=["CLNSIG", "CLNDN","CLNDISDB"]
names=["clinvar_pathogenic","clinvar_disease_name","clinvar_dbInfo"]
ops=["self","self","self"]

# Cosmic variants
[[annotation]]
file="GEMINI-2019/gemini_data/cosmic-v68-GRCh37.tidy.vcf.gz"
fields=["ID"]
names=["cosmic_ids"]
ops=["uniq"]

# Fitcons
[[annotation]]
file="GEMINI-2019/gemini_data/hg19_fitcons_fc-i6-0_V1-01.bed.gz"
columns=[4]
names=["fitcons_float"]
ops=["mean"]

# not sure what these are, encode I guess?
[[annotation]]
file="GEMINI-2019/gemini_data/encode.6celltypes.consensus.bedg.gz"
#chrom   start   end     gm12878 h1hesc  helas3  hepg2   huvec   k562
columns=[4,5,6,7,8,9]
ops=["concat","concat", "concat", "concat", "concat", "concat"]
names=[ "encode_consensus_gm12878", "encode_consensus_h1hesc", "encode_consensus_helas3", "encode_consensus_hepg2", "encode_consensus_huvec", "encode_consensus_k562"]

# Gwas hits
[[annotation]]
file="GEMINI-2019/gemini_data/hg19.gwas.bed.gz"
columns=[4]
names=["gwas_pubmed_trait"]
ops=["uniq"]

# Repeat masked regions
[[annotation]]
file="GEMINI-2019/gemini_data/hg19.rmsk.bed.gz"
columns=[4]
names=["rmsk"]
ops=["uniq"]

# GERP Elements
[[annotation]]
file="GEMINI-2019/gemini_data/hg19.gerp.elements.bed.gz"
columns=[4]
names=["gerp_elements"]
ops=["mean"]

#CpG Islands
[[annotation]]
file="GEMINI-2019/gemini_data/hg19.CpG.bed.gz"
columns=[2]
names=["cpg_island"]
ops=["flag"]

#Seg Dups
[[annotation]]
file="GEMINI-2019/gemini_data/hg19.segdup.bed.gz"
columns=[2]
names=["in_segdup"]
ops=["flag"]

# RLCRs
[[annotation]]
file="RLCRs_no_repeatMaster.bed.gz"
columns=[2]
names=["in_rlcr"]
ops=["flag"]

# DGV hits
[[annotation]]
file="GEMINI-2019/gemini_data/hg19.dgv.bed.gz"
columns=[4]
names=["dgv"]
ops=["uniq"]

# TFBSs (NEED TO UPDATE THIS TO JASPAR)
[[annotation]]
file="GEMINI-2019/gemini_data/wgEncodeRegTfbsClusteredV2.cell_count.20130213.bed.gz"
columns=[4]
names=["tfbs"]
ops=["uniq"]

# HapMap II
[[annotation]]
file="GEMINI-2019/gemini_data/genetic_map_HapMapII_GRCh37.gz"
columns=[4, 5]
ops=["mean", "mean"]
names=["hapmap1", "hapmap2"]

# DNAse open regions
[[annotation]]
file="GEMINI-2019/gemini_data/stam.125cells.dnaseI.hg19.bed.gz"
columns=[5, 6]
ops=["mean", "uniq"]
names=["stam_mean", "stam_names"]

# Not sure what this is, CSE - HiSeq?
[[annotation]]
file="GEMINI-2019/gemini_data/cse-hiseq-8_4-2013-02-20.bed.gz"
columns=[2]
ops=["flag"]
names=["cse-hiseq"]

# CADD
# Updated to v1.4
[[annotation]]
file="CADD/v1.4/whole_genome_SNVs.tsv.gz"
names=["CADD"]
columns=[6]
ops=["self"]

# CADD InDel
[[annotation]]
file="CADD/v1.4/InDels.tsv.gz"
names=["CADD_indel"]
columns=[6]
ops=["self"]

# PolyPhen2
[[annotation]]
file="PolyPhen2/polyphen2.txt.gz"
names=["pp2hdiv", "pp2hvar"]
columns=[5, 6]
ops=["max", "max"]

# High Confidence Regions
[[annotation]]
file="ConfidentRegions/ConfidentRegions.bed.gz"
columns=[2]
names=["ConfidentRegion"]
ops=["flag"]



