configfile: "config.yaml"

miniconda = config['miniconda']

rule all: 
    input: directory("gatk-4.1.0.0")

rule activate_conda: 
    input: "environment.yml", test=config["miniconda"]
    output: directory(miniconda + "/envs/AnnotateVariants")
    shell: "conda env create -f {input}"

rule install_GATK:
    input: directory(miniconda + "/envs/AnnotateVariants")
    output: "gatk-4.1.0.0.zip",
            directory("gatk-4.1.0.0")
    shell: "wget https://github.com/broadinstitute/gatk/releases/download/4.1.0.0/gatk-4.1.0.0.zip && unzip gatk-4.1.0.0.zip"

# rule install_GEMINI: 
# rule download_db: