name: AnnotateVariants
channels:
  - bioconda
  - defaults
dependencies:
  - bcftools=1.9
  - bwa=0.7.17
  - gatk=3.8
  - htslib=1.9
  - picard=2.18.27
  - samtools=1.9
  - snpeff=4.3.1t
  - vcf2db=2018.10.26
  - vcfanno=0.3.1
  - vt=2015.11.10

